name: "help.md generator"
description: "Generate help.md and push to GitHub"
author: tsubasaogawa

inputs:
  binary_path:
    description: "Target binary path (ex. /bin/cat)"
    required: true
  cmd:
    description: "Additional commands for binary (ex. --help)"
    required: false
    default: "--help"
  title:
    description: "Markdown title"
    required: false
    default: "Help"
  artifact_path:
    description: "Path of a generated artifact"
    required: false
    default: "help.md"
  working_directory:
    description: "Working directory"
    required: false
    default: "."

outputs:
  committed:
    description: "1 if file is committed"
    value: "1" # ${{ steps.push.outputs.committed }}

runs:
  using: "composite"
  steps:
    - name: Validation
      run: |
        set -e
        which "${{ inputs.binary_path }}"
        test "${{ inputs.title }}" != ""
        test "${{ inputs.artifact_path }}" != ""
        test -e "${{ inputs.working_directory }}"
      shell: bash
    - name: Run binary
      run: ${{ inputs.binary_path }} ${{ inputs.cmd }} > /tmp/out.log
      shell: bash
    - name: Generate md
      run: |
        sed \
          -e "1i # ${{ inputs.title }}" /tmp/out.log \
          -e '2i \\' \
          -e '3i ```bash' \
          -e '$a ```' \
          -e '$a \\' \
          > ${{ inputs.artifact_path }}
      shell: bash
      working-directory: ${{ inputs.working_directory }}
    - name: Push generated atom file
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update ${{ inputs.artifact_path }}
        commit_author: GitHub Actions <actions@github.com>
        repository: ${{ inputs.working_directory }}

branding:
  icon: "file"
  color: "purple"
