name: "Test for help.md generator"
on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        uses: tsubasaogawa/help-md-generator@main
        with:
          binary_path: "/bin/cat"
          cmd: "--help"
          title: "cat help"
          artifact_path: ".github/workflows/sample_help.md"
          working_directory: "."
